// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v7.34.0
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface CreateUserDto {
  username: string;
  password: string;
  age: number;
}

export interface Empty {
}

export interface FindOneUserDto {
  id: string;
}

export interface UpdateUserDto {
  id: string;
  socialMedia: SocialMedia | undefined;
}

export interface Users {
  users: User[];
}

export interface User {
  id: string;
  username: string;
  password: string;
  age: string;
  subscribed: boolean;
  socialMedia: SocialMedia | undefined;
}

export interface SocialMedia {
  twitterUri?: string | undefined;
  fbUrl?: string | undefined;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface UsersServiceClient {
  /** Creates a new user and returns the created user */

  createUser(request: CreateUserDto): Observable<User>;

  /** find all Users and return all users */

  findAllUsers(request: Empty): Observable<Users>;

  /** find one user and return that user */

  findOneUser(request: FindOneUserDto): Observable<User>;

  /** update user and return that user */

  updateUser(request: UpdateUserDto): Observable<User>;

  /** find and remove user and return user */

  removeUser(request: FindOneUserDto): Observable<User>;
}

export interface UsersServiceController {
  /** Creates a new user and returns the created user */

  createUser(request: CreateUserDto): Promise<User> | Observable<User> | User;

  /** find all Users and return all users */

  findAllUsers(request: Empty): Promise<Users> | Observable<Users> | Users;

  /** find one user and return that user */

  findOneUser(request: FindOneUserDto): Promise<User> | Observable<User> | User;

  /** update user and return that user */

  updateUser(request: UpdateUserDto): Promise<User> | Observable<User> | User;

  /** find and remove user and return user */

  removeUser(request: FindOneUserDto): Promise<User> | Observable<User> | User;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "findAllUsers", "findOneUser", "updateUser", "removeUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
